branches:
  only:
    - master
language: swift
os: osx
osx_image: xcode9
cache:
  - cocoapods
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=CocoaPods
script:
- |
  if [ "$TEST_TYPE" = iOS ]; then
    set -o pipefail
    make all
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint Themify.podspec
  fi
